/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.offbreach;

import com.github.britooo.looca.api.util.Conversor;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author rafae
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public Timer timer = new Timer();
    public DatabaseConnection dbConnection = new DatabaseConnection();
    public HardwareData data = new HardwareData();
    public User usuario = new User();
    public MainPage() {
        initComponents();
    }

    static MainPage mainPage = new MainPage();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        dadosServidorView = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dadosServidorTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hostnameLabel = new javax.swing.JLabel();
        hostnameValue = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        statusValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        dataInitLabel = new javax.swing.JLabel();
        dataInitValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        usoRamLabel = new javax.swing.JLabel();
        usoRamValue = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        usoCpuLabel = new javax.swing.JLabel();
        usoCpuValue = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        usoDiscoLabel = new javax.swing.JLabel();
        usoDiscoValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(9, 80, 111));
        header.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        footer.setBackground(new java.awt.Color(9, 80, 111));
        footer.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        main.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 10));

        dadosServidorView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dadosServidorView.setPreferredSize(new java.awt.Dimension(300, 200));
        dadosServidorView.setLayout(new javax.swing.BoxLayout(dadosServidorView, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dadosServidorTitulo.setText("Dados do Servidor");
        jPanel2.add(dadosServidorTitulo);

        dadosServidorView.add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        hostnameLabel.setText("Hostname:");
        jPanel3.add(hostnameLabel);

        hostnameValue.setText("------");
        jPanel3.add(hostnameValue);

        dadosServidorView.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        statusLabel.setText("Status:");
        jPanel4.add(statusLabel);

        statusValue.setText("------");
        jPanel4.add(statusValue);

        dadosServidorView.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dataInitLabel.setText("Data de Inicialização:");
        jPanel5.add(dataInitLabel);

        dataInitValue.setText("--/--/-- --:--");
        jPanel5.add(dataInitValue);

        dadosServidorView.add(jPanel5);

        main.add(dadosServidorView);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("Data dos Recursos");
        jPanel6.add(jLabel8);

        jPanel1.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        usoRamLabel.setText("Uso da Ram:");
        jPanel7.add(usoRamLabel);

        usoRamValue.setText("0%");
        jPanel7.add(usoRamValue);

        jPanel1.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        usoCpuLabel.setText("Uso Cpu:");
        jPanel8.add(usoCpuLabel);

        usoCpuValue.setText("0%");
        jPanel8.add(usoCpuValue);

        jPanel1.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        usoDiscoLabel.setText("Uso Discos:");
        jPanel9.add(usoDiscoLabel);

        usoDiscoValue.setText("0");
        jPanel9.add(usoDiscoValue);

        jPanel1.add(jPanel9);

        main.add(jPanel1);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String username = "";

    /**
     * @param user the command line arguments
     */

    public void setUserName(User user) {
        this.username = user.getNome();
    }

    public void setUser(User user){
        this.usuario = user;
    }

    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainPage.setVisible(true);
            }
        });
    }

    public void getLoocaData() {
        data.setHostname();
        String tempCpuValue = String.format("%.1f", data.getProcessador().getUso());
        usoCpuValue.setText(tempCpuValue + "%");
        dataInitValue.setText(Conversor.formatarSegundosDecorridos(data.getSistema().getTempoDeAtividade()));
        usoRamValue.setText(data.getMemoriaEmUso());
        statusValue.setText("Ativo");
        usoDiscoValue.setText(Conversor.formatarBytes(data.getDiscoData().get(0).getLeituras()));
        hostnameValue.setText(data.getHostname());
    }

    public void trySaveInLoop() {
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                dbConnection.saveCpuAndMemoryDataInLoop(usuario);
                getLoocaData();
            }
        }, 0, 3000);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dadosServidorTitulo;
    private javax.swing.JPanel dadosServidorView;
    private javax.swing.JLabel dataInitLabel;
    private javax.swing.JLabel dataInitValue;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JLabel hostnameValue;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel main;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusValue;
    private javax.swing.JLabel usoCpuLabel;
    private javax.swing.JLabel usoCpuValue;
    private javax.swing.JLabel usoDiscoLabel;
    private javax.swing.JLabel usoDiscoValue;
    private javax.swing.JLabel usoRamLabel;
    private javax.swing.JLabel usoRamValue;
    // End of variables declaration//GEN-END:variables
}
